#!/bin/bash

set -e

# Determine the version of PostgreSQL.
if [ -z ${1+x} ]; then
    echo "ERROR: No PostgreSQL version number passed to $0"
    echo "Usage:"
    echo "  $0 \$PGVERSION"
    exit 2
fi

PGVERSION=${1:-}

apt-get update
apt-get install -y --no-install-recommends \
        build-essential clang llvm llvm-dev llvm-runtime cmake \
        ca-certificates gnupg2 curl libicu-dev libxml2 locales ssl-cert libxml2-utils
apt-get -y purge postgres*

curl https://salsa.debian.org/postgresql/postgresql-common/-/raw/master/pgdg/apt.postgresql.org.sh -O --output-dir  /usr/local/bin/
chmod +x /usr/local/bin/apt.postgresql.org.sh

apt.postgresql.org.sh -i -v "$PGVERSION"
chmod a+rwx "$(pg_config --pkglibdir)" "$(pg_config --sharedir)/extension"

pg_createcluster --start "$PGVERSION" test -p "${PGPORT:-5433}" -- -A trust || true
